id: P000437
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5481
  title: མཁས་དབང་ཚུལ་ཁྲིམས་བློ་གྲོས་ཀྱི་བཀའ་སློབ།
  author: ''
  volumes:
    7dfe94ba75a74d13adb27160f48be71a:
      image_group_id: I3CN5483
      title: Volume 1 of dus thog char pa/
      volume_number: 1
      total_pages: 297
      base_file: v001.txt
ebook_metadata:
  title: མཁས་དབང་ཚུལ་ཁྲིམས་བློ་གྲོས་ཀྱི་བཀའ་སློབ།
  author: ''
  sku: P000437
  cover: cover.jpg
  layers:
  - pagination
